title: ruby-jp
description: |
  perches は 若手エンジニアのためのプログラミングサークル

lang: ja
timezone: Asia/Tokyo

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/

theme: jekyll-theme-cayman

github_username: perches-team

slack_invite_link: https://join.slack.com/t/perches/shared_invite/enQtNTQ2NTE0NDUyMzA1LTQzMTRiZWNkODYwNGI2NWYzN2Q0MjI1NGQzMGM0MjgyNTg4NWU5YjcyYmE3MmMwMzEzYWFmZmVkYWQyNTk2ZGY
